[package]
name = "xilem-error-messages"
version = "0.1.0"
edition = "2024"

[dependencies]
xilem = { git = "https://github.com/linebender/xilem/", version = "0.4.0", rev = "7385e3dbe954d9f0ec12c9272428ba681e742a6f" }
